if(CMAKE_SYSTEM_NAME MATCHES "Linux")
	if(CMAKE_CROSSCOMPILING)
		message(STATUS "TODO: future embeded system")
	else(CMAKE_CROSSCOMPILING)
		include("${GUIDANCE_PLATFORMS_PATH}/linux64/Configs.cmake")
	endif(CMAKE_CROSSCOMPILING)
elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
	if("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
		include("${GUIDANCE_PLATFORMS_PATH}/win64/Configs.cmake")
	else()
		include("${GUIDANCE_PLATFORMS_PATH}/win32/Configs.cmake")
	endif()
endif()
