if(CMAKE_SYSTEM_NAME MATCHES "Linux")
	if(CMAKE_CROSSCOMPILING)
		message(STATUS "TODO: future embeded system")
	else(CMAKE_CROSSCOMPILING)
		include("${GUIDANCE_PLATFORMS_PATH}/linux64/Configs.cmake")
	endif(CMAKE_CROSSCOMPILING)
elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
	include("${GUIDANCE_PLATFORMS_PATH}/win64/Configs.cmake")
endif()
